name: Broken Links Checker
on:
  pull_request:
    branches: [ master ]
jobs:
  Broken_Link_Checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout PR
        uses: dawidd6/action-checkout-pr@v1
        with:
          pr: ${{ github.event.pull_request.number }}
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: "src/pages"
          use-quiet-mode: "yes"
          config-file: ".github/workflows/brokenlinks-config.json"
